// Replace the sample copy and media here when the couple's final details arrive.
export const wedding = {
  bride: "Jasmin Sopera",
  groom: "Anjo Caluya",
  date: "Saturday, November 21, 2026",
  dateDisplay: "November 21, 2026",
  countdownDate: "2026-11-21T00:00:00+08:00",
  hashtag: "#JasTheOneForAnjo",
  time: "Time to be confirmed",
  ceremony: "San Bartolome Parish",
  reception: "St. John XXIII Hall",
  location: "San Bartolome Parish, Malabon",
  story: [
    { date: "01", title: "An unexpected beginning", description: "Sometimes, the loveliest things begin in the most ordinary ways. A simple hello became a conversation neither of us wanted to end—and, little by little, a friendship became something more." },
    { date: "02", title: "Our favorite everyday", description: "Through coffee dates, spontaneous adventures, and the quiet comfort of being together, we discovered that home could be a person. In every season, we kept choosing each other." },
    { date: "03", title: "A lifetime of yes", description: "One heartfelt question opened the door to our next chapter. Now, surrounded by the people who have loved us along the way, we begin our greatest adventure: forever." },
  ],
  program: [
    { time: "2:30 PM", title: "Welcome, loved ones", description: "Arrive, settle in, and share a little excitement." },
    { time: "3:00 PM", title: "We say “I do”", description: "A celebration of faith, love, and a lifetime together." },
    { time: "4:30 PM", title: "A moment to remember", description: "Photographs with our families and dearest friends." },
    { time: "5:30 PM", title: "To love & laughter", description: "Dinner, heartfelt toasts, and a beautiful evening." },
    { time: "7:00 PM", title: "Under the same stars", description: "Our first dance, sweet moments, and celebrations." },
  ],
  entourage: [
    { role: "Parents of the bride", names: ["Mr. Roberto Sopera", "Mrs. Elena Sopera"] },
    { role: "Parents of the groom", names: ["Mr. Antonio Caluya", "Mrs. Maria Caluya"] },
    { role: "Maid of honor", names: ["Isabel Santos"] },
    { role: "Best man", names: ["Miguel Reyes"] },
    { role: "Bridesmaids", names: ["Sofia Garcia", "Camille Cruz", "Andrea Mendoza"] },
    { role: "Groomsmen", names: ["Gabriel Santos", "Rafael Cruz", "Daniel Flores"] },
    { role: "Principal sponsors", names: ["Mr. & Mrs. Ricardo Santos", "Mr. & Mrs. Eduardo Reyes"] },
    { role: "Secondary sponsors", names: ["Candle · Patricia & Carlo", "Veil · Nicole & Paolo", "Cord · Bianca & Marco"] },
    { role: "Little companions", names: ["Ring bearer · Lucas", "Coin bearer · Mateo", "Flower girl · Olivia"] },
  ],
  palette: [
    { name: "Champagne", color: "#e9dfc3" }, { name: "Peach", color: "#f3bea6" },
    { name: "Blush", color: "#f3c3cf" }, { name: "Powder blue", color: "#bbd4ee" },
    { name: "Lilac", color: "#e8c4ec" }, { name: "Butter", color: "#f8f3ce" },
    { name: "Sage", color: "#d3dfb2" },
  ],
};
