export const sapphireMistInvitation = {
  debutante: {
    firstName: "Claudia",
    fullName: "Claudia Isabelle Reyes",
    nickname: "Clau",
  },
  event: {
    date: "2030-10-15T18:00:00+08:00",
    displayDate: "October 15, 2030",
    time: "6:00 PM",
    venue: "The Glass Garden",
    address: "257 Evangelista Avenue, Pasig City, Metro Manila",
    dressCode: "Shades of blue · Cocktail formal",
    directionsUrl:
      "https://www.google.com/maps/search/?api=1&query=The+Glass+Garden+Pasig+City",
  },
  copy: {
    eyebrow: "A Night Written in Blue",
    welcome:
      "Eighteen years of memories, dreams, and beautiful beginnings. Join us as we celebrate a new chapter under a sky of sapphire dreams.",
    quote:
      "She carries stardust in her eyes and whole new worlds in her heart.",
  },
  funFacts: [
    { label: "Her happy place", value: "Anywhere with music" },
    { label: "Current obsession", value: "Film photography" },
    { label: "Always ordering", value: "Iced matcha" },
    { label: "Dream destination", value: "Lake Como" },
  ],
  timeline: [
    { time: "5:00 PM", title: "Guest Arrival", detail: "Cocktails beneath the blue hour" },
    { time: "6:00 PM", title: "Grand Entrance", detail: "The night officially begins" },
    { time: "6:30 PM", title: "Dinner", detail: "A sapphire feast with family & friends" },
    { time: "7:30 PM", title: "18 Traditions", detail: "Stories, wishes, and cherished moments" },
    { time: "9:00 PM", title: "Party & Celebration", detail: "Meet us under the lights" },
  ],
  traditions: [
    {
      number: "01",
      title: "18 Roses",
      copy: "A dance for every chapter, guided by the people who helped her bloom.",
      members: [
        { name: "Miguel Reyes", relation: "Father" },
        { name: "Mateo Reyes", relation: "Brother" },
        { name: "Rafael Santos", relation: "Grandfather" },
        { name: "Daniel Cruz", relation: "Uncle" },
        { name: "Joaquin Reyes", relation: "Cousin" },
        { name: "Gabriel Mendoza", relation: "Cousin" },
        { name: "Enzo Villanueva", relation: "Childhood friend" },
        { name: "Lucas Navarro", relation: "School friend" },
        { name: "Nathan Lim", relation: "Family friend" },
        { name: "Liam Garcia", relation: "Friend" },
        { name: "Sebastian Flores", relation: "Friend" },
        { name: "Andre Castillo", relation: "Friend" },
        { name: "Marco Dela Peña", relation: "Family friend" },
        { name: "Paolo Tan", relation: "Classmate" },
        { name: "Ethan Ramos", relation: "Classmate" },
        { name: "Joshua Aquino", relation: "Friend" },
        { name: "Luis Santiago", relation: "Friend" },
        { name: "Adrian Valdez", relation: "Escort" },
      ],
    },
    {
      number: "02",
      title: "18 Candles",
      copy: "Eighteen lights, each carrying a wish for the beautiful years ahead.",
      members: [
        { name: "Catherine Reyes", relation: "Mother" },
        { name: "Isabel Santos", relation: "Grandmother" },
        { name: "Patricia Cruz", relation: "Aunt" },
        { name: "Bianca Reyes", relation: "Sister" },
        { name: "Sofia Mendoza", relation: "Cousin" },
        { name: "Angela Villanueva", relation: "Godmother" },
        { name: "Camille Navarro", relation: "Childhood friend" },
        { name: "Chloe Lim", relation: "Best friend" },
        { name: "Danica Garcia", relation: "School friend" },
        { name: "Elise Flores", relation: "Friend" },
        { name: "Frances Castillo", relation: "Friend" },
        { name: "Gia Dela Peña", relation: "Family friend" },
        { name: "Hannah Tan", relation: "Classmate" },
        { name: "Iris Ramos", relation: "Classmate" },
        { name: "Janelle Aquino", relation: "Friend" },
        { name: "Kyla Santiago", relation: "Friend" },
        { name: "Lara Valdez", relation: "Friend" },
        { name: "Mika Soriano", relation: "Best friend" },
      ],
    },
    {
      number: "03",
      title: "18 Treasures",
      copy: "Small keepsakes chosen with meaning, memory, and a little bit of magic.",
      members: [
        { name: "Teresa Reyes", relation: "Grandmother" },
        { name: "Veronica Santos", relation: "Aunt" },
        { name: "Monica Cruz", relation: "Aunt" },
        { name: "Nina Mendoza", relation: "Godmother" },
        { name: "Olivia Villanueva", relation: "Cousin" },
        { name: "Pia Navarro", relation: "Cousin" },
        { name: "Queenie Lim", relation: "Family friend" },
        { name: "Rhea Garcia", relation: "Family friend" },
        { name: "Sam Flores", relation: "Friend" },
        { name: "Talia Castillo", relation: "Friend" },
        { name: "Una Dela Peña", relation: "Friend" },
        { name: "Vera Tan", relation: "Classmate" },
        { name: "Wynne Ramos", relation: "Classmate" },
        { name: "Xandra Aquino", relation: "Friend" },
        { name: "Yana Santiago", relation: "Friend" },
        { name: "Zoe Valdez", relation: "Friend" },
        { name: "Amara Soriano", relation: "Mentor" },
        { name: "Bella Manalo", relation: "Best friend" },
      ],
    },
    {
      number: "04",
      title: "18 Shots",
      copy: "A joyful toast to courage, laughter, and the adventures still unwritten.",
      members: [
        { name: "Alyssa Mercado", relation: "Best friend" },
        { name: "Bea Dominguez", relation: "Childhood friend" },
        { name: "Carla Evangelista", relation: "School friend" },
        { name: "Denise Bautista", relation: "Friend" },
        { name: "Erika Salazar", relation: "Friend" },
        { name: "Faith Cabrera", relation: "Friend" },
        { name: "Gabby Macaraeg", relation: "Classmate" },
        { name: "Hazel Pascual", relation: "Classmate" },
        { name: "Ina Velasco", relation: "Friend" },
        { name: "Jamie Co", relation: "Friend" },
        { name: "Katrina Sy", relation: "Friend" },
        { name: "Lexi Chua", relation: "Friend" },
        { name: "Mae Lorenzo", relation: "Cousin" },
        { name: "Nicole Robles", relation: "Cousin" },
        { name: "Patty Yulo", relation: "Family friend" },
        { name: "Reese Araneta", relation: "Friend" },
        { name: "Trina Katigbak", relation: "Friend" },
        { name: "Ysa Del Rosario", relation: "Best friend" },
      ],
    },
  ],
} as const;

export type SapphireMistInvitation = typeof sapphireMistInvitation;
