// Event and entourage details transcribed from the couple's printed invitation.
export const wedding = {
  bride: "Jasmin Sopera",
  groom: "Anjo Caluya",
  date: "Saturday, November 21, 2026",
  dateDisplay: "November 21, 2026",
  countdownDate: "2026-11-21T15:00:00+08:00",
  hashtag: "#JAStheoneforANJO",
  time: "3:00 PM",
  ceremony: "San Bartolome Parish",
  reception: "St. John XXIII Hall",
  receptionFloor: "2/F",
  location: "San Bartolome Parish, Malabon",
  story: [
    { date: "01", title: "An unexpected beginning", description: "Sometimes, the loveliest things begin in the most ordinary ways. A simple hello became a conversation neither of us wanted to end—and, little by little, a friendship became something more." },
    { date: "02", title: "Our favorite everyday", description: "Through coffee dates, spontaneous adventures, and the quiet comfort of being together, we discovered that home could be a person. In every season, we kept choosing each other." },
    { date: "03", title: "A lifetime of yes", description: "One heartfelt question opened the door to our next chapter. Now, surrounded by the people who have loved us along the way, we begin our greatest adventure: forever." },
  ],
  program: [
    { time: "3:00 PM", title: "Ceremony", description: "Join us as we exchange our vows." },
    { time: "4:00 PM", title: "Photos", description: "Capture memories with our families and friends." },
    { time: "5:00 PM", title: "Guest Registration & Cocktails", description: "Check in and enjoy cocktails before the reception program." },
    { time: "6:00 PM", title: "Reception Program", description: "Join us for the reception program." },
    { time: "7:30 PM", title: "Dinner", description: "Share a meal as we celebrate together." },
    { time: "10:00 PM", title: "Party", description: "Let the celebration continue!" },
  ],
  entourage: [
    { role: "Parents of the groom", names: ["Mr. Alberto Caluya (+)", "Mrs. Lodivina Caluya (+)"] },
    { role: "Parents of the bride", names: ["Mr. Oscar Sopera", "Mrs. Jocelyn Sopera"] },
    { role: "Principal sponsors", names: [
      "Ms. Jane Gonzales", "Mr. Alvin Yapan",
      "Mrs. Dorcas Desiderio", "Mr. Rogelio Desiderio Jr.",
      "Mrs. Aurora Partée", "Mr. Marcel Partée",
      "Mrs. Deborah Marquez", "Mr. Rodolfo Marquez",
      "Mrs. Rosa-Liza Napaton", "Mr. Armando Napaton",
      "Mr. Felix William Fuentebella", "Mr. Macario Gayeta",
      "Mr. Engelbert Apostol", "Mr. Russell Samson",
    ] },
    { role: "Maid of honor", names: ["Ms. Jackie Lyn Barcebal"] },
    { role: "Best man", names: ["Mr. Jonathan Toledo"] },
    { role: "Bridesmaids", names: ["Ms. Joanna Marie Nodado", "Ms. Daisy Sopera", "Ms. Jennifer Ortiz", "Ms. Hannah Marie Stacey Delos Santos", "Mrs. Lovely Precious Ganipan"] },
    { role: "Groomsmen", names: ["Mr. Edcel Colon", "Mr. Rodee Kaye Conde", "Mr. Paul Vincent Espinas", "Mr. Jayvee Patenga", "Mr. Jomer Tomale"] },
    { role: "Candle", names: ["Ms. Jennifer Santiago", "Mr. Jel Santos"] },
    { role: "Cord", names: ["Ms. Veronica Aco", "Mr. Kent Kevin Nieves"] },
    { role: "Veil", names: ["Mrs. Jeanne Pauline De Guzman", "Mr. Mark Japhet Marquez"] },
    { role: "Bible bearer", names: ["Dirk Alistair Jean Ortiz"] },
    { role: "Coin bearer", names: ["Jace Johan Catalan"] },
    { role: "Ring bearer", names: ["Zac Christian Ezekiel Ganipan"] },
    { role: "Flower girls", names: ["Amyra Kristal Caluya", "Zyline Kassie Guianan"] },
  ],
  palette: [
    { name: "Champagne", color: "#ede2c6" }, { name: "Peach", color: "#fbc4a6" },
    { name: "Blush", color: "#fdc7d5" }, { name: "Powder blue", color: "#bbd6f3" },
    { name: "Lilac", color: "#ffc9fd" }, { name: "Butter yellow", color: "#fffdd7" },
    { name: "Sage", color: "#d6deaf" }, { name: "Lavender", color: "#d3b4f4" },
  ],
};
