-- Run this migration in the Supabase SQL editor before enabling live RSVP
-- collection for Nylgen and Kersee.

create table if not exists public.nylgen_kersee_rsvps (
  id bigint generated by default as identity primary key,
  attendee_name text not null
    check (char_length(attendee_name) between 2 and 150),
  attendance_status text not null
    check (attendance_status in ('attending', 'declined')),
  contact_number text not null
    check (char_length(contact_number) between 6 and 40),
  email text not null
    check (char_length(email) <= 254),
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.nylgen_kersee_rsvps enable row level security;

-- The website writes through its server-only Supabase secret key. Do not add
-- anonymous insert or select policies for this table.

create index if not exists nylgen_kersee_rsvps_attendance_idx
  on public.nylgen_kersee_rsvps (attendance_status);

create index if not exists nylgen_kersee_rsvps_submitted_at_idx
  on public.nylgen_kersee_rsvps (submitted_at desc);
